# Generated by Django 3.2.5 on 2021-07-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('host_id', models.IntegerField(max_length=50)),
                ('host_name', models.CharField(max_length=500)),
                ('neighbourhood_group', models.CharField(max_length=500)),
                ('neighbourhood', models.IntegerField(max_length=50)),
                ('latitude', models.FloatField(max_length=5)),
                ('longitude', models.FloatField(max_length=5)),
                ('room_type', models.CharField(max_length=500)),
                ('price', models.FloatField(max_length=20)),
                ('minimum_nights', models.IntegerField(max_length=5)),
                ('number_of_reviews', models.FloatField(max_length=20)),
                ('last_review', models.DateField(max_length=20)),
                ('reviews_per_month', models.IntegerField(max_length=20)),
                ('calculated_host_listings_count', models.IntegerField(max_length=20)),
                ('availability_365', models.IntegerField(max_length=20)),
            ],
        ),
    ]
