# Generated by Django 3.2.5 on 2021-07-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='reviews_per_month',
            field=models.FloatField(max_length=20),
        ),
    ]
