# Generated by Django 3.2.5 on 2021-07-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='availability_365',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='calculated_host_listings_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='last_review',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='minimum_nights',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='neighbourhood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='number_of_reviews',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='reviews_per_month',
            field=models.FloatField(),
        ),
    ]
