# Generated by Django 3.2.5 on 2021-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listings_last_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='last_review',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(),
        ),
    ]
