# Generated by Django 3.2.5 on 2021-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210716_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='neighbourhood',
            field=models.CharField(max_length=500),
        ),
    ]
