# Generated by Django 3.2.5 on 2021-07-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listings_neighbourhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='neighbourhood_group',
        ),
    ]
