# Generated by Django 3.2.5 on 2021-07-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listings_neighbourhood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='last_review',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='reviews_per_month',
        ),
    ]
