# Generated by Django 3.2.5 on 2021-07-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210716_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='availability_365',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='calculated_host_listings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='minimum_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='number_of_reviews',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
