# Generated by Django 3.2.5 on 2021-07-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210716_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='host_name',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
